language: java
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out local.secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out local.pubring.gpg
  -d
install: mvn install -DskipTests=true -Dgpg.skip=true
script:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then mvn clean verify deploy --settings settings.xml
  -Dgpg.passphrase=$ENCRYPTION_PASSWORD; else mvn clean verify -Dgpg.skip=true; fi
env:
  matrix:
    secure: vtSC+cUfEC4I8QAT1UwRNHhm8MS5HViOJ+vrUc06i1JoRG9LliOXXS5Ib0JKJ6UdQDNmIXSEpioFBekNs8I/ECnABBB0yUMDvfzKtz3Jk73M0WVusQ65bTghThtnsjkM65rb65O5/axD5Gk/G+wAM0U46leA9wf2VHr4brWHI2WGfMzkazQWRkhtquccPQxZF+9Ah7g+AX2UKLClQsFwPbLNg1/wT+LVplaMCn9+9tI2eZaaLNi6MA/+DfyMmh+am5UCn70CMQmPFRJXpBgJk0i9tqYXz2+PnE7HMlARP8nwStD2vXRcvz3C8cHjMoSf0DXiV2YgdS26G9iVfqDj1GVARGY+SOm+PUsZUuf5c6Q5icBVOQgBu345tBT3G3IrvYbx2vFqc77EC1G9DDBsWg251Z+SA6xPoKWwFcTCRZkbsW4Zi2QhdHTHTq5aJzhWGPYL5qDIqZVT6IdkvGKCA2sIDYCy+Pk0jpqaKibv7yMQ5K6Bg3qKuVLqQc89nBwYPYprckKqCxoqML00GjlwMJZ9WWSifsznnBWHW1nMPPqOQTchjqcy38yF+yOwmzKlb1q1u6FQVO0c5lHkw2BbQovGEVPogmaWyNlfgf1jdrq4GTWJ03cjjfvIkUyaOZOHcyEfnCpyu3O8Kxqog3l+0JFwYcl7wvoYKHgc0sD1lsU=
